### ISSUE TITLE
Add Alias Name

### ISSUE THREAD

**Issue by maherz1229** [bluenote10/typed_argparse#7]
This is helpful actually.

Could you add this feature to set the original name or alias?
Because there are some arguments with long name and I want to simplify/shorten the name from the class.

like this:

```python
class Test(TypedArgs):
    git: str

parser = argparse.ArgumentParser()
parser.add_argument('-g', '--github',)
```

Which will throw an error:
```python
TypeError: Arguments object is missing argument 'git'
```

With pydantic we can use something like this:

```python
class Test(BaseModel):
     git: str = pydantic.Field(alias="github")
```

**Comment by bluenote10** [comment]
You can simply solve that on the `argparse` level itself:

```python
parser.add_argument('-g', '--github', dest='git')
```

Basically typed_argparse is an ultra lightweight pydantic (e.g. 56 kB vs 35 MB in the virtualenv) with a focus on argparse integration. For now I wanted to avoid having class instance variables, because I'm afraid they would add quite a bit of complexity.

**Comment by maherz1229** [comment]
Alright. Thank you. I will reinstall this now :)

**Comment by bluenote10** [comment]
Hope this works for you, feel free to re-open otherwise ;)
